server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webmvc:
          globalcors:
            add-to-config-global-store: true
            cors-configurations:
              '[/**]':
                allowedOrigins:
                - "http://localhost:5173"
                - "http://136.110.213.76:80"
                - "https://medportal-frontend-35457515854.asia-south1.run.app"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true

          routes:
            - id: appointment-service
              uri: lb://APPOINTMENT-SERVICE
              predicates:
                - Path=/api/v1/appointments/**

            - id: patient-service
              uri: lb://APPOINTMENT-SERVICE
              predicates:
                - Path=/api/v1/patients/**

            - id: doctor-service
              uri: lb://APPOINTMENT-SERVICE
              predicates:
                - Path=/api/v1/doctors/**

            - id: clinical-record-service
              uri: lb://CLINICAL-RECORD-SERVICE
              predicates:
                - Path=/api/v1/records/**

            - id: lab-report-service
              uri: lb://LAB-REPORT-SERVICE
              predicates:
                - Path=/api/v1/lab-reports/**

eureka:
  client:
    service-url:
      defaultZone: http://vm-node-a.platform:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: gateway,health