server.port=8083

# GCP Cloud Storage Bucket Details
gcp.bucket.name=medportal-lab-reports-bucket
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Cloud SQL Connection
spring.datasource.url=jdbc:mysql://34.93.196.20:3306/lab_report_db?createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=Asd713@#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update

# Eureka Discovery Settings
eureka.client.enabled=true
eureka.client.service-url.defaultZone=http://vm-node-a.platform:8761/eureka/